/**
 * @archivo   TipoEventoIntento.ts
 * @descripcion Enumera los eventos auditables del ciclo de vida del intento.
 * @modulo    Enums
 * @autor     EvalPro
 * @fecha     2026-03-15
 */
export enum TipoEventoIntento {
  EVALUACION_ABIERTA = 'EVALUACION_ABIERTA',
  INTENTO_INICIADO = 'INTENTO_INICIADO',
  RESPUESTA_SELECCIONADA = 'RESPUESTA_SELECCIONADA',
  RESPUESTA_CAMBIADA = 'RESPUESTA_CAMBIADA',
  RESPUESTA_LIMPIADA = 'RESPUESTA_LIMPIADA',
  APP_EN_BACKGROUND = 'APP_EN_BACKGROUND',
  APP_EN_FOREGROUND = 'APP_EN_FOREGROUND',
  INCIDENTE_REGISTRADO = 'INCIDENTE_REGISTRADO',
  REINGRESO_AUTORIZADO = 'REINGRESO_AUTORIZADO',
  TOKEN_REINGRESO_CONSUMIDO = 'TOKEN_REINGRESO_CONSUMIDO',
  ENVIO_SOLICITADO = 'ENVIO_SOLICITADO',
  FINALIZACION_PROVISIONAL = 'FINALIZACION_PROVISIONAL',
  RECONCILIACION_EXITOSA = 'RECONCILIACION_EXITOSA',
  RECONCILIACION_FALLIDA = 'RECONCILIACION_FALLIDA',
  RESULTADO_PUBLICADO = 'RESULTADO_PUBLICADO',
  ANULACION = 'ANULACION',
}
