/**
 * @archivo   TipoEventoTelemetria.ts
 * @descripcion Enumera los eventos de telemetría usados para trazabilidad y fraude.
 * @modulo    Enums
 * @autor     EvalPro
 * @fecha     2026-03-02
 */
export enum TipoEventoTelemetria {
  INICIO_EXAMEN = 'INICIO_EXAMEN',
  CAMBIO_PREGUNTA = 'CAMBIO_PREGUNTA',
  RESPUESTA_GUARDADA = 'RESPUESTA_GUARDADA',
  APLICACION_EN_SEGUNDO_PLANO = 'APLICACION_EN_SEGUNDO_PLANO',
  PANTALLA_ABANDONADA = 'PANTALLA_ABANDONADA',
  CAPTURA_BLOQUEADA = 'CAPTURA_BLOQUEADA',
  FORZAR_CIERRE = 'FORZAR_CIERRE',
  SESION_INVALIDA = 'SESION_INVALIDA',
  EXAMEN_ENVIADO = 'EXAMEN_ENVIADO',
  SINCRONIZACION_COMPLETADA = 'SINCRONIZACION_COMPLETADA',
}
