/**
 * @archivo   TipoIncidente.ts
 * @descripcion Enumera incidentes de seguridad aplicables sobre un intento.
 * @modulo    Enums
 * @autor     EvalPro
 * @fecha     2026-03-15
 */
export enum TipoIncidente {
  APP_EN_BACKGROUND = 'APP_EN_BACKGROUND',
  PERDIDA_DE_FOCO = 'PERDIDA_DE_FOCO',
  NAVEGACION_NO_AUTORIZADA = 'NAVEGACION_NO_AUTORIZADA',
  OVERLAY_DETECTADO = 'OVERLAY_DETECTADO',
  VERIFICACION_INTEGRIDAD_FALLIDA = 'VERIFICACION_INTEGRIDAD_FALLIDA',
  INCONSISTENCIA_SINCRONIZACION = 'INCONSISTENCIA_SINCRONIZACION',
  COMPORTAMIENTO_DUPLICADO_SOSPECHOSO = 'COMPORTAMIENTO_DUPLICADO_SOSPECHOSO',
  TOKEN_REINGRESO_INVALIDO = 'TOKEN_REINGRESO_INVALIDO',
  TIEMPO_EXCEDIDO = 'TIEMPO_EXCEDIDO',
  RECONCILIACION_INCONSISTENTE = 'RECONCILIACION_INCONSISTENTE',
}
