@echo off
setlocal

set LOG_RUTA=%~dp0..\..\backend-3101.log

set PUERTO_APP=3101
set HOST_APP=127.0.0.1
set ENTORNO=pruebas
set INTEGRIDAD_REQUERIR_REPORTE_ANDROID=true
set INTEGRIDAD_REQUERIR_BLOQUEO_ESTRICTO_ANDROID=false
set INTEGRIDAD_PERMITIR_EMULADOR=true
set INTEGRIDAD_PERMITIR_COMPILACION_DEBUG=true
set INTEGRIDAD_PERMITIR_OPCIONES_DESARROLLADOR=true
set INTEGRIDAD_PERMITIR_ADB=true
set INTEGRIDAD_RIESGO_BLOQUEO_UMBRAL=90

cd /d "%~dp0.."
call npm run start:prod >> "%LOG_RUTA%" 2>&1
